defaults: &defaults
  enable_gallery: true
  enable_comments: true
  comments_disqus_pageid: 'jdsoo89eorl'
  show_booking_info: true

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
  enable_gallery: false
  enable_comments: false
  comments_disqus_pageid: 'gfdytt7368gf='
